### ISSUE TITLE
Question: using poser.Function()

### ISSUE THREAD

**Issue by bttmly** [bevacqua/poser#4]
Not an issue, just a question I'm wondering if you have any thoughts on how to use `poser.Function()`? I'd like to do something like the following so I can extend a poser `Function.prototype` with things like `curry`, `partial`, etc. I believe any solution will necessarily involve either `new Function()` or `eval` but even with that borderline black magic I haven't been able to crack it.

``` js
var PoserFunc = poser.Function()
PoserFunc.prototype.curry = // etc.
PoserFunc.prototype.partial = // etc.

// is there any way to write this function!?
function wizardry (fn) {
// does some magic, returns an instance of PoserFunc which delegates to fn
}

var addTwo = wizardry(function(a, b) {
  return a + b;
});

addTwo.curry() // curried function
addTwo.curry()(1)(2) // 3

addTwo.partial(1) // partially applied function
addTwo.partial(1)(2) // 3

// etc...
```

Thanks! I really like the Poser concept, really want to play around with it more.

**Comment by bevacqua** [comment]
For a usage example check out [`dominus`](https://github.com/bevacqua/dominus), it makes extensive use of `poser.Array()`. The trick is to provide all of the necessary instantiation through your API. In the case of `dominus`, the array instances are provided to you by Dominus whenever you query the DOM.

I think functions are a bit trickier because you'd have to use the the [`new Function` form](http://www.tutorialspoint.com/javascript/javascript_function_constructors.htm) which is sort of an eval.

Basically, I'm saying:

``` js
var a = /function\s*\(([\w, ]*)\)/i // matches arguments
var b = /{(.*)}\s*$/; // matches body

function trim (text) {
  return text.trim();
}

function wizardry (fn) {
  var text = fn.toString();
  var args = text.match(a).split(',').map(trim);
  var body = text.match(body);
  args.push(body);
  return fun(args); // you can't just (new Function).apply..
}

function fun (args) {
  if (args.length === 1) {
    return new PoserFunc(args[0]);
  } else if (args.length === 2) {
    return new PoserFunc(args[0], args[1]);
  } else // etc ..
}
```

I'm not sure if this would be practical, because the scope is probably going to change, but other than that it'd be doable.

**Comment by bttmly** [comment]
Thanks for the feedback! I'm hoping to keep `fn` scope the same so I want to avoid `.toString`. I'm going to try creating the `wizardry` function within the other execution context.

**Comment by bttmly** [comment]
@bevacqua In case you're interested here's what I came up with:
(not working right now in Chrome; perhaps related to [this](https://code.google.com/p/chromium/issues/detail?id=412173), but looks promising in Canary)

``` js
var wizardry = (function() {
  var code = "(function (fn) { return function () { return fn.apply(this, arguments); }; })"
  var frame = document.createElement('iframe');
  frame.style.display = 'none';
  document.body.appendChild(frame);
  var win = frame.contentWindow;
  wEval = win.eval.bind(win);
  return wEval(code);
})();
// the prototype is at Object.getPrototypeOf(wizardry);
var proto = Object.getPrototypeOf(wizardry);

// then we can do cool stuff like...
proto.newMethod = function () {}

var addTwo = wizardry(function(a, b) { return a + b; });
addTwo instanceof Function // false
addTwo(1, 2) // 3
typeof addTwo.newMethod // "function"

var funcWClosure = (function() {
  var x = 10;
  return function () {
    return x;
  }
})();
var wrappedFuncWClosure = wizardry(funcWClosure);

wrappedFuncWClosure() // 10
wrappedFuncWClosure instanceof Function // false
```
